"""Hadron stable release metadata."""

APP_NAME = "Hadron"
__version__ = "3.0.0"
SCHEMA_VERSION = 12

PUBLISHER_NAME = "bxane"
PUBLISHER_GITHUB = "bxane-dev"
RELEASE_REPOSITORY = "bxane-dev/hadron"
RELEASE_REPOSITORY_URL = "https://github.com/bxane-dev/hadron"
RELEASE_API_URL = "https://api.github.com/repos/bxane-dev/hadron/releases/latest"

PROJECT_FORMAT_VERSION = 1
WORKSPACE_BUNDLE_VERSION = 1
RELEASE_MANIFEST_VERSION = 1
RELEASE_SIGNATURE_VERSION = 1
CAPSULE_FORMAT_VERSION = 1
REPRODUCTION_REPORT_VERSION = 1
REGRESSION_REPORT_VERSION = 1
REGRESSION_BASELINE_VERSION = 1
CAMPAIGN_FORMAT_VERSION = 1
CAMPAIGN_REFERENCE_VERSION = 1
CAMPAIGN_RUN_VERSION = 1
PIPELINE_FORMAT_VERSION = 1
PIPELINE_RUN_VERSION = 1
RECOVERY_BUNDLE_VERSION = 1

STABLE_FORMAT_EPOCH = 3
